
site:
  short_name: "NV Health Link"
  long_name: ""

  call_center:
    name: "NV Health Link's Customer Care Center"
    phone_number: "1-855-768-5465"

aca:
  state_name: "Nevada"
  state_abbreviation: "NV"
  ivl:
    enrollment_due_day_of_month: 15
  shop:
    retroactive_termination_maximum: 60.days
    renewal_period_before_start_on_maximum: 3.months
